name = "ShiftShares"
uuid = "f9c67564-f18b-4724-8d82-3b2309aceff9"
authors = ["Junyuan Chen <norman.chen.git@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"

[compat]
CSV = "0.10"
CodecZlib = "0.7"
DataFrames = "1"
FixedEffectModels = "1.6"
julia = "1.3"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "CodecZlib", "Test"]
